
[smbc-5]

cmd = "./smbc.native --check --depth-step 5 -nc $file"
unsat = "result UNSAT"
sat = "result SAT"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[smbc-30]

cmd = "./smbc.native --check --depth-step 30 -nc $file"
unsat = "result UNSAT"
sat = "result SAT"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[test]

timeout=30
problems = ".*.lisp"
provers = [ "smbc-5", "smbc-30" ]
dir = [ "examples" ]


