provers = [ "smbc-1", "smbc-5", "smbc-30" ]

[smbc-1]

binary = "./smbc"
cmd = "ulimit ; ./smbc --check --depth-step 1 -t $timeout -nc $file"
unsat = "result UNSAT"
sat = "result SAT"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"
version = "git:."


[smbc-5]

binary = "./smbc"
cmd = "./smbc --check --depth-step 5 -t $timeout -nc $file"
unsat = "result UNSAT"
sat = "result SAT"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"
version = "git:."

[smbc-30]

binary = "./smbc"
cmd = "./smbc --check --depth-step 30 -t $timeout -nc $file"
unsat = "result UNSAT"
sat = "result SAT"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"
version = "git:."

[test]

timeout=30
problems = ".*.smt2"
provers = [ "smbc-1", "smbc-5", "smbc-30" ]
dir = [ "examples" ]


